grafana:
  ingress:
    enabled: false
    # For public Grafana with custom domain + TLS, replace these values with real ones and enable ingress.
    # ingressClassName: alb
    # annotations:
    #   alb.ingress.kubernetes.io/scheme: internet-facing
    #   alb.ingress.kubernetes.io/target-type: ip
    #   alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    #   alb.ingress.kubernetes.io/ssl-redirect: "443"
    #   alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:<ACCOUNT_ID>:certificate/<CERTIFICATE_ID>
    # hosts:
    #   - grafana.<YOUR_DOMAIN>
    path: /
    pathType: Prefix

  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password

  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 7d
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
