apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-external-secret
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: prod/mysql_secret
        property: DB_HOST
    - secretKey: DB_NAME
      remoteRef:
        key: prod/mysql_secret
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: prod/mysql_secret
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/mysql_secret
        property: DB_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: prod/mysql_secret
        property: DATABASE_URL