apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretstore
  namespace: prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: eso-prod-sa