apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-external-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: monitoring/grafana_secret
        property: GRAFANA_USERNAME
    - secretKey: admin-password
      remoteRef:
        key: monitoring/grafana_secret
        property: GRAFANA_PASSWORD