apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-kibana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/awaismansha-00/production-grade-devsecops.git
    targetRevision: main
    path: k8s/observability/logging

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true