apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://jaegertracing.github.io/helm-charts
      chart: jaeger
      targetRevision: 3.3.3
      helm:
        releaseName: jaeger
        valueFiles:
          - $values/helm-values/tracing/jaeger-values.yaml

    - repoURL: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true