apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-external-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: monitoring_secret
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_USERNAME
      remoteRef:
        key: monitoring/grafana_secret
        property: GRAFANA_USERNAME
    - secretKey: GRAFANA_PASSWORD
      remoteRef:
        key: monitoring/grafana_secret
        property: GRAFANA_PASSWORD